// <auto-generated />
using ListaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ListaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241105074745_initialmigration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ListaAPI.Models.ZakupyToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZakupyToDoName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("zakupyToDos");
                });
#pragma warning restore 612, 618
        }
    }
}
